app = "part11-blog-app"
primary_region = "arn"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3003"
  MONGODB_URI = "mongodb+srv://samw0907:EadDuryan1706%21@atlascluster.fjk6ysb.mongodb.net/bloglistApp?retryWrites=true&w=majority"
  NODE_ENV = "production"
  VITE_API_URL = "https://part11-blog-app.fly.dev"  # Set production API URL

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
