# fly.toml app configuration file generated for blog-app-misty-sky-7448 on 2024-12-10T17:07:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blog-app-misty-sky-7448"
primary_region = "arn"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "3003"
  MONGODB_URI = "mongodb+srv://samw0907:EadDuryan1706%21@atlascluster.fjk6ysb.mongodb.net/bloglistApp?retryWrites=true&w=majority"
  NODE_ENV = "production"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
