name: Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: npm install

      - name: Install ESLint globally
        run: npm install -g eslint
        
      - name: Lint backend code
        run: npx eslint . --fix

      - name: Build frontend
        run: |
          cd bloglist-frontend
          npm install
          npx eslint . --fix
          npm run build

      - name: Copy dist to backend build directory
        run: |
          cp -r bloglist-frontend/dist/* ./build/

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "FLYCTL_INSTALL=$HOME/.fly" >> $GITHUB_ENV
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV


      - name: Deploy app to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


      - name: Notify Success to Discord
        if: success()
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            **A new version of BlogApp deployed**
            - To (https://part11-blog-app.fly.dev/) by: ${{ github.actor }}
            - Severity: :green_circle: Informational

      # Optionally notify on failure
 #     - name: Notify Failure to Discord
 #       if: failure()
 #       uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
 #       env:
 #         DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
 #       with:
 #         args: |
 #           **Build failed**
 #           - Commit (https://github.com/${{ github.repository }}/commit/${{ github.sha }}) by ${{ github.actor }} broke the build :(
 #           - Severity: :red_circle: Error
